services:
  mysql:
    image: mysql:8.0.36

    restart: always

    container_name: local-mysql-container

    ports:
      - 3308:3306

    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: interviewpartner
      TZ: Asia/Seoul

    volumes:
      - mysql:/var/lib/mysql
      # - ./:/docker-entrypoint-initdb.d

    networks:
      - my-network

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --log-error-verbosity=1

  redis:
    image: redis:7.2.4
    restart: always
    container_name: local-redis-container
    ports:
      - 6379:6379
    networks:
      - my-network
    volumes:
      - redis:/data

  openvidu:
    image: openvidu/openvidu-dev:2.29.0
    restart: always
    container_name: local-openvidu-container
    ports:
      - 4443:4443
    environment:
      OPENVIDU_SECRET: zxczxcxztiasdasdsaJFtestMpP1231231234
      DOMAIN_OR_PUBLIC_IP: localhost
      OPENVIDU_WEBHOOK: true
      OPENVIDU_WEBHOOK_ENDPOINT: http://host.docker.internal:8080/webhook
      OPENVIDU_WEBHOOK_HEADERS: '["Authorization: Basic cm9vdDpyb290MTIzNA=="]'
      OPENVIDU_WEBHOOK_EVENTS: '["sessionDestroyed","participantJoined", "participantLeft", "signalSent"]'
    networks:
      - my-network
volumes:
  mysql:
  redis:

networks:
  my-network:
    driver: bridge
