spring:
  config:
    activate:
      on-profile: prod
    import: aws-parameterstore:/config/interviewpartner/

  datasource:
    url: ${DATABASE_URL}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      repositories:
        enabled: false
  rabbitmq:
    addresses: ${RABBITMQ_ADDRESSES}
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    ssl:
      enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  application:
    name: interviewpartner
  ssl:
    enabled: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: ${JWT_SECRET}
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: https://interviewpartner.site/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: https://interviewpartner.site/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope: account_email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false
    time-zone: Asia/Seoul

oauth2:
  redirect:
    success-url: https://interviewpartner.site/login?status=success
    failure-url: https://interviewpartner.site/login?status=failure&error=

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api/v1/docs
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true

cloud:
  aws:
    cloudfront:
      domain: ${CLOUDFRONT_DOMAIN}
    s3:
      bucket: ${S3_BUCKET}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
openvidu:
  url: ${OPENVIDU_URL}
  secret: ${OPENVIDU_SECRET}

gpt:
  credentials:
    secretKey: ${GPT_KEY}
google:
  cloud:
    credentials:
      encoded: ${GOOGLE_STT_CREDENTIALS}

logging:
  level:
    root: info
